### PR TITLE
Simplify some functions, fix a test

### PR DESCRIPTION
**Pull request by jstepien**
I hope that renaming and rewriting in 867ed12 is compatible with your idea of how this fn should work.

Have a sunny afternoon!

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by ifesdjeen** [comment]
w000t

**Comment by ifesdjeen** [comment]
@jstepien released `1.0.5`

**Comment by jstepien** [comment]
Great, cheers!

**Pull request merged**
